### ISSUE TITLE
Add support for graylisting

### ISSUE THREAD

**Issue by davidkarlsen** [saltstack-formulas/postfix-formula#11]
Hi again @nmadhok .
I'm thinking on adding support for greylisting as well (using postgrey), see: http://rimuhosting.com/knowledgebase/linux/mail/greylisting%20with%20postgrey for the concept.
Again it will be hard to parameterize due to how main.cf is generated by using all the pillar values as parameters.
Should I create a pull request for it like for spf?

**Comment by nmadhok** [comment]
@davidkarlsen How about we create s new formula called postgrey-formula for this and put it there?

**Comment by gravyboat** [comment]
I'd agree, different, app, different formula. +1 @nmadhok

**Comment by davidkarlsen** [comment]
How to handle the conflicting management of main.cf?

**Comment by aboe76** [comment]
It would be cool though saltstack formula could figure out or detect if postgrey-formula is also used in the same rendering of the highstate on the minion and configure it in the main.cf
something like 
````
{% if salt.state('postgrey') %}
do_something:
  something
{% endif %}

**Comment by gravyboat** [comment]
Could always rip main.cf out of the config file, then you just include whichever one you need.

**Comment by aboe76** [comment]
@gravyboat and @nmadhok postgrey I think postgrey isn't used standalone,
In the name it implies postfix:  Postfix Greylisting Policy Server

So I don't think a separate formula is the way to go, because of the interconnection with main.cf it should be in postfix-formula as a separate state, postfix.postgrey, would work.

**Comment by davidkarlsen** [comment]
@aboe76 was it fixed?

**Comment by aboe76** [comment]
@davidkarlsen there is postfix.postgrey.sls in the formula which should work.
