### ISSUE TITLE
grains['fqdn'] lookup in pillar

### ISSUE THREAD

**Issue by variia** [saltstack-formulas/postfix-formula#12]
Please do not promote this, using grain lookup in pillar is BAD idea. Pillar is compiled on master, cashed on minion, so your pillar will feature master's 'fqdn' not the the targeted server. (maybe the same in your test case)

**Comment by nmadhok** [comment]
@variia you're right! Can you submit a PR for this? https://github.com/saltstack-formulas/postfix-formula/commit/6286442d75cfd3ae3e6d531d647007f79688b0d8 Needs to be reverted.

**Comment by variia** [comment]
Sorry, unable to do at this stage. I am in the process of restoring lost content due to hardware failure, my dev env is not recovered yet.

**Comment by gravyboat** [comment]
@nmadhok Looks like this might be fixed here? https://github.com/saltstack-formulas/postfix-formula/blob/d13d7f75198b0befb19fe69fde0356815514c0b3/postfix/files/main.cf#L41#L43

If we just add a set value at the top that might do the job.

**Comment by davidkarlsen** [comment]
Haven't really changed any of that.
My change was to add localhost.localdomain in the state (not the pillar) in https://github.com/saltstack-formulas/postfix-formula/commit/2faeb5ea5f882ac37d25ca13af5c083fec7a23fe - and the invention of the set_parameter macro was done in https://github.com/saltstack-formulas/postfix-formula/commit/78f3a47becded54bf5eefad5d2da6673de5b855e . 

But it's just about removing the bad habit of using grains in pillars in the example - so just go ahead and remove it? Or you want a pull req?

**Comment by davidkarlsen** [comment]
Looking at http://salt.readthedocs.org/en/latest/topics/pillar/ it seems to be in order with what's in the docs for chpt 5/5.1?

**Comment by variia** [comment]
Sure, my issue is the example only hence phrased like 'promote'. I don't question funcionality.

**Comment by variia** [comment]
I can do a pull request if you want and update the pillar.example if you guys agree otherwise just close it?

**Comment by nmadhok** [comment]
@variia that would be great.
