### ISSUE TITLE
pillar example

### ISSUE THREAD

**Issue by campbellmc** [saltstack-formulas/postfix-formula#36]
I believe line 29 in the pillar example should have a colon rather than =

-    smtp_tls_CApath = /etc/ssl/certs
+    smtp_tls_CApath: '/etc/ssl/certs'

**Comment by gravyboat** [comment]
Thanks for noting this, if you would like to make a PR feel free to do so.

**Comment by campbellmc** [comment]
@gravyboat There's a PR to fix this now.

**Comment by gravyboat** [comment]
Good stuff, thank you.
