### ISSUE TITLE
myhostname parameter: is fqdn or myhostname pillar data used?

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/postfix-formula#44]
Hello,

I just discovered this formula which I try to use. I see in pillar.example there is a parameter called

    config:
      myhostname: localhost

I thought it will be used to manage the 'myhostname' Postfix parameter, which seems to not be the case: in https://github.com/saltstack-formulas/postfix-formula/blob/master/postfix/files/main.cf#L74 I see

    {{ set_parameter('myhostname', grains['fqdn']) }}

It this normal, did I miss something? _(I'm quite new to salt)_

Thanks.

**Comment by aboe76** [comment]
Hi @daks, this is normal, the first part set_parameter will look up the parameter 'myhostname' in pillar,
if it is found it will use that, otherwise it will fallback to a default value the second part, grains 'fqdn'
which means it will use the fqdn grain of the minion as value.

**Comment by daks** [comment]
Ok, so I need to check my setup because I don't have this behavior. Thanks for your quick answer.

**Comment by aboe76** [comment]
does the pillar top.sls file load the pillar file?

**Comment by daks** [comment]
I thought it does, but I may have a problem there.

  $ ls pillar/
  postfix.sls  top.sls

  $ cat top.sls
  base:
    '*':
      - postfix

I'm using Vagrant with masterless salt provisioning (but I use salt-call state.apply instead of reloading my vm).
When I make a typo in top.sls, I got an error but I'm not sure it loads the postfix.sls pillar file.

**Comment by aboe76** [comment]
@daks , the code looks good, could you do a 
```salt-call pillar.item postfix```

**Comment by daks** [comment]
It works and returns

```
local:
    ----------
    postfix:
        ----------
        config:
            ----------
            myhostname:
                host.example.org
```

weird.

**Comment by aboe76** [comment]
@daks try
```
salt-call state.apply postfix.config
```

**Comment by daks** [comment]
it works now. That means that my state doesn't include postfix.
```
$ ls salt/
top.sls    postfix/
$ cat top.sls
base:
  '*':
    - postfix
```
and the postfix directory is the one from your formula.

**Comment by daks** [comment]
Maybe this is the problem, I need to add postfix.config to my state?

**Comment by aboe76** [comment]
yes, that's the solution, you can ditch the postfix state, in favor of postfix.config, 
please look at the sls files and there you see include: - postfix.

**Comment by daks** [comment]
Yes, it works. Thank your very much for your help.
