### ISSUE TITLE
/usr/sbin/postconf: warning: /etc/postfix/main.cf: unused parameter: compatibility_level=2

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/postfix-formula#45]
Hello,

on Debian 7.11 (oldstable) with Postfix 2.9.6-2, this formula sets this parameter in main.cf

     compatibility_level = 2

and when restarting the service, I got this warning

    /usr/sbin/postconf: warning: /etc/postfix/main.cf: unused parameter: compatibility_level=2

**Comment by gravyboat** [comment]
We could definitely add some sort of `if version` check, but since it's just a warning and Debian 7 is EOL as of April 2016 (minus LTS) I'm mostly against it and would suggest that you modify the settings on your fork of the formula. If you want to propose a PR to add this we can definitely see about adding it though.

**Comment by daks** [comment]
If it doesn't affect Debian 8, I understand. I'll look closer to see how I can remove this warning on my install or propose a PR.

**Comment by gravyboat** [comment]
I think it's mostly the older version of Postfix that is the problem (I checked and the latest is 2.11.something and not available for Debian 7). It seems they change or add variables for the configuration file occasionally and this problem crops up for a lot of people. You could try just deleting https://github.com/saltstack-formulas/postfix-formula/blob/master/postfix/files/main.cf#L29 and that should fix it.

**Comment by daks** [comment]
I would like to not fork the formula, so either:

- I keep this parameter which creates a warning each time the service is restarted
- I try to 'extend' to remove this parameter, I don't know if it's possible or not but I'll try

**Comment by gravyboat** [comment]
If you decide not to make changes you should still fork the formula so you don't get unexpected changes that we may merge. Relying on the master branch of a formula repo can result in unintended consequences.

**Comment by aboe76** [comment]
You can set:
```
compatibility_level:
```
in your pillar, without data then it will be an empty parameter.

**Comment by daks** [comment]
@gravyboat yes, I know and I will.
@aboe76 this is really nice! It works as expected and ease my job. Thanks :)
