### ISSUE TITLE
aliases may be broken

### ISSUE THREAD

**Issue by saxonww** [saltstack-formulas/postfix-formula#6]
I am trying to use this formula on CentOS 7. I have a pillar like this:

```
postfix:
  relayhost: relay.example.com
  inet_interfaces: localhost
  aliases: |
    # Basic system aliases -- these MUST be present.
    mailer-daemon:  postmaster
    postmaster:     root
    root: user@example.com
```

Due to the arbitrary parameter change (78f3a47becded54bf5eefad5d2da6673de5b855e) recently accepted, the content of pillar['postfix']['aliases'] is included in the main.cf file. Since this is not valid main.cf content, both postfix and run-newaliases fail.

**Comment by rhertzog** [comment]
The same happens with "virtual".
