### ISSUE TITLE
os equals RedHat does not account for variants such as CentOS

### ISSUE THREAD

**Issue by colin-stubbs** [saltstack-formulas/postfix-formula#68]
The 'os' grain is NOT 'RedHat' on a 'CentOS' system, and likely different on others. This causes the policyd-spf state to break as it does not know which package to install.

The formula needs to map on os_family grain before os; or simply add CentOS to osmap.yaml

e.g.

[root@box ~]# salt 'box' grains.get os_family
box:
    RedHat
[root@box ~]# salt 'box' grains.get os
box:
    CentOS
[root@box ~]#

Yes, this is with 2017.7.4

[root@box ~]# salt --versions
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: 1.10.6
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.3.8
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: 0.1.3
 msgpack-python: 0.5.1
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: 0.6.5
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

[root@box ~]#

**Comment by javierbertoli** [comment]
This should be fixed on #79
