### ISSUE TITLE
Add support for SPF

### ISSUE THREAD

**Issue by davidkarlsen** [saltstack-formulas/postfix-formula#8]
See https://help.ubuntu.com/community/Postfix/SPF
I'd be happy to submit a pull request for adding postfix-policyd-spf-python into the formula.
I think it will be hard to parameterize/make optional (the way pillar is used at the moment) as it requires handling master.cf and putting check_policy_service unix:private/policy-spf into main.cf in the correct place - but it seems sensible to activate SPF checks by default?

**Comment by davidkarlsen** [comment]
ping?

**Comment by nmadhok** [comment]
Submit a PR and I will review it @davidkarlsen
Please tag me on the PR.
